---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: accountingservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OTEL_EXPORTER_OTLP_ENDPOINT: AgADr54Gn7BSohtC3McVo3O5ii+vUJKqL8+8vjxJEb7q8N7SYSDrP3E0ztLWX1XEKJQjTMGFX9nAo1YwoHCw0vLHr1Q1XdckXQyqIkbYvACKJiG8X9KP1SMvQXwj47wY7tgpek+OuK5W2suH2AaERYpgqLAh3acoO54oK+5Oq0lLYw/G4RzAKjwpBQd2IlQr/986pl2jOsyq4eDMKBD4qXG+yq51OsQq++A1aPmXFYCdFd3ZXJbshw6zs/OzfWC2H7iQMW+wep84m4OjGnjA2DlNbvvI0Np8p94mYilW0v+hyWZfIgSNkYysTw/2wpeQptBWFJpJCw+pBloq2Jb8SFoGxWjEBW6PmxDgWZaemvlC3e0eIIE99pK6PDGebhQUajyobxw3pYNPJV8qDnFT9KXISOYCV6vVmFiQAhAXY7+nWkPbDGL4DZD42nPOTqGwOmAzLJq7V5j8hHokwYzQs59VaQVD3hjKzd05b2cz6FWnOSlIzticmA4oXGfBbjUv0i1hIJsdff+RMztdec54sKMq5yW69xw0XwMntE0Jk3koVlkTVD35DSmcm76sDd6h3M3c0lgG7qD3SGkdn9eeAziUkronCt4n8zZsjQrcZTM249Kz4TysGKMi4NAH79TPKA+8zitw4Vel7X6oogaCvcuO9Sl9x2Ez9WpFGSqx5X32rrlzwqd3+flLjGZidi7KuBdcDqFVC88M7mG41JQJfQfIuPlAJnfcG0cbMfXZNtok9re7R4tQcQ==
  template:
    metadata:
      name: accountingservice-secret
      namespace: ecommerce-dev
    type: Opaque
