apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patches/frontend-deployment.yaml
  - path: patches/frontendproxy-deployment.yaml
  - path: patches/kafka-deployment.yaml
  - path: patches/llmservice-deployment.yaml
  - path: patches/paymentservice-deployment.yaml
  - path: patches/cartservice-deployment.yaml
  - path: patches/productcatalogservice-deployment.yaml
