apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  labels:
    app: valkey
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  serviceName: valkey-headless
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:7.2-alpine
          imagePullPolicy: IfNotPresent
          command:
            - valkey-server
            - --appendonly
            - "yes"
          ports:
            - containerPort: 6379
              name: valkey
          envFrom:
            - configMapRef:
                name: valkey-config
          resources:
            limits:
              memory: 20Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - name: valkey-data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
