apiVersion: v1
kind: ConfigMap
metadata:
  name: loadgenerator-config
data:
  OTEL_SERVICE_NAME: "loadgenerator"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-demo-otelcol:4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=loadgenerator,service.namespace=opentelemetry-demo,service.version=1.12.0"
  LOCUST_WEB_PORT: "8089"
  LOCUST_USERS: "10"
  LOCUST_SPAWN_RATE: "1"
  LOCUST_HOST: "http://frontendproxy:8080"
  LOCUST_HEADLESS: "false"
  LOCUST_AUTOSTART: "true"
  LOCUST_BROWSER_TRAFFIC_ENABLED: "true"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"