apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - name: tcp-service
      port: 8080
      targetPort: 8080