---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OTEL_EXPORTER_OTLP_ENDPOINT: AgAO2vhyT4eV0JbCX3X3EtdHI+LSG6kROAEi1XE/AdPAGhyLOTXPzUlRP32rZ+7FhmAMj26o7e3nVo1I+xAA9DVv8afT29m6wfhmwNobF+/yjlkg28oez8Xcw0VPr7OCH6x1JbFtJF177b9JVZxOdGBwdWnN0JP+HPVOSCYOjjWbmg3gqPG+f3FcZO+eLI4I8gmGIoG+TlNIMI/Bbuv0Wo+D/N+vfYmpZjLC0vQWM1dbOAp4Iph/g+Lj5H4MDt8GVTkV4MdM/J7bQG4L3rSgU62hcHL9+Z4BHFCOBPptrt2pkZTrwYF0GFsg6tmxFpp27V+jWNZpmoTveq4bPX79HhExEULDuKfr0/bA7sCJ0UJ5njaDvmP2k+Ajx2UiHAiI8A5LDuBsy1aBR6Z/RggeQI0o4FRJGvJvUlDvnYZlhdmA5ly3MW6d7FEDePJLCjERVYfy2ze2cghFPfDcpQ72kbI93WQfO0ZglM+bLXdqbj04+SrNEbEiM8HouvzpNBe3uD2awlISc+Me7E2DWpA0cP9vcAATT0eVXtGbERv+Q1YCiiAigih0kcvmgo5Ti5Z2CRaYOBPyCXEj98xReE3roezc0QeVxjyqWk74eZH2AyQ34xkkDeayWztDfKi5GuZ4Qv8PosaDJKZp1Kf20GTif0SOpukHAQv6I3vJ++bnkErZUDmqILlWb8EeXytMq7Po5IKUI5OEx6fAhegB8LNtRdb6+HJiiAeaAdoIcF256xUR/5tYiu8O6w==
  template:
    metadata:
      name: kafka-secret
      namespace: ecommerce-dev
    type: Opaque
