apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: alb-ingress-patch.yaml
  - path: patches/frontend-deployment.yaml

