apiVersion: v1
kind: Secret
metadata:
  name: paymentservice-secret
type: Opaque
stringData:
  PAYMENT_PROVIDER_API_KEY: "dummy-payment-api-key"
  PAYMENT_PROVIDER_SECRET: "dummy-payment-secret"
  STRIPE_WEBHOOK_SECRET: "dummy-webhook-secret"
  ENCRYPTION_KEY: "dummy-encryption-key-123"