apiVersion: v1
kind: ConfigMap
metadata:
  name: imageprovider-config
data:
  OTEL_SERVICE_NAME: "imageprovider"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_COLLECTOR_HOST: "opentelemetry-demo-otelcol"
  OTEL_COLLECTOR_PORT_GRPC: "4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=imageprovider,service.namespace=opentelemetry-demo,service.version=1.12.0"
  IMAGE_PROVIDER_PORT: "8081"