apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prod
  namespace: argocd
  labels:
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedyasser002/kustomize-argoCD.git
    targetRevision: main
    path: overlays/prod         
  destination:
    server: https://kubernetes.default.svc
    namespace: prod           
  syncPolicy:
    automated:
      prune: true
      selfHeal: false          
    syncOptions:
      - CreateNamespace=false