apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmservice
  labels:
    app: llmservice
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: llmservice
  template:
    metadata:
      labels:
        app: llmservice
    spec:
      containers:
        - name: llmservice
          image: ghcr.io/open-telemetry/demo:latest-llm

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: service
          livenessProbe:
            httpGet:
              path: /v1/models
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/models
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: llmservice-config
            - secretRef:
                name: llmservice-secret
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"