---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: llmservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    OPENAI_API_KEY: AgAtuT8jHFw4ltnku5RfT61QPtTgpWkC9nWBYtxteOZsLQZq88UeASGntRgV+OywVZQlPtQxcXidsj4N2UqbVIFmL1ps9N+28iekqWAB7rMPav0XC0gPAUtLAJihQJCMrn8lgBnWKW4cVsYTFaBB2hWkIDCE5xRpzBGjAGDsTOYC4KyA50h8tJoIvucnxMmBRXJrmgRssDFTFbOeUVZ2CHe5KTDf95xiyTLPRCO6d6fjMUaaZ5RbuRO+LKNeEnsNyiU3qPTA9YY4ly3E53sXDprgAkOCMJmYtXv0KhLoVEPQkiLq0xFRct4AVvvKCRCWDmKHoNZqYMwc+lc+7g7FHl+G5xifGILMMgPcZOQlghv6Tj7zIm5KwpcQAC6E07A8sHD1PyKQkNgsdv0RX/3whyz+RpfG8RXo8i8XkLHrYSlPbnIyI0+Xi5903QrUkoOvtRnxog/btofiyDerNJj+Tc+uRvRg+HgNKAq0xF9WpKgps5E4MXMpiB5TVemoXhBoFPq8QCD/ZlvXSmDYKXpRBVXQzP7p+pVrf+X+ZDYRbldAvIDTJOnS36sp29QHd11fqk0kZFrzBDHpTw3rwVAO14eE6Ngq77osj7qx6gCNHz4zlqmawGPmC2AT/haey0h1GZYZaKhRCEXtDvK+9P1WiWAoh8162MTh5u4QIK7OrD6yKX33FYh8JHiq6HRb6CrhnLqqGMaveZxWMgrbVNnHXuXZbxJvBw==
    OTEL_EXPORTER_OTLP_HEADERS: AgBPCz913DPrIGa+bLPtJqHfUeq6L6Ic84NMGxG3sq3zYR86Hwwwvs94EeL6ON1Aw6L97oaPW+xYJJzcMoqYQvulII3XargjV3B8qSfpKR0RGw2gpUBvU6qsC3pIaI+MTesWNuYEhI8HkS0a/cL0/1flb0DbEm8W3xm35Anz2aM2MhPpg1X2vR5YmM7wR0EzUcCWwz686zZ5UOQdMogs/JRAan4xhpq0pkj2cwDnvrrUqawdRB66ar6xlLJMhle8LcucjtbMLSR+xNmNHU4hQhpOK3RMYcJNaJKaLHGgusWx1hq54jLk6VS+IyM20saqvzWdxTTNRsZI30uitzzjoeJhHTc40vNT995EqiM6wkjJaoBXgkuywrgZOr+mD5x4cE1ZSBuZWZaPcVP/r4iaUx0TCil+fFM9ZOjZZlwmOqkN/fp3/Y4rSVllQOh/BQNukihriN7oCSk2xUZclFx2EmUfVwqV6pTH17/vhvcBiNsgCG+SRDSw1eJvXy0WfTGPzhKgofz4p4kMhCRX1atxb7k2U/RnibOTwY2lLFs+XraYSjahg3yCZRQVKhebzRsYuXotoNnYCkiKKBjpbolP17YfVNnyCMBg1Wg7GkgY/hZ/mGMh3fG9jIpm4rfHdoMFDEqtyGx33Luyo3LQqeAd1SZLfqioFBtIA/sL3t1TftXNZctMyvxlpWWNQW4gu/yPlbHCl6/M8RPu9g5X6/DVjyPJ7Okn7vVIFU9bXTeMJMsw5g==
  template:
    metadata:
      name: llmservice-secret
      namespace: ecommerce-dev
    type: Opaque
