apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
  - kafka
  - accounting
  - ad
  - valkey
  - cart
  - checkout
  - currency
  - email
  - flagd
  - frauddetection
  - frontend
  - imageprovider
  - loadgenerator
  - payment
  - productcatalog
  - quote
  - recommendation
  - shipping
  - llm
  - postgres
  - productreview
  - frontendproxy
  - collector

