apiVersion: v1
kind: ConfigMap
metadata:
  name: frauddetectionservice-config
data:
  OTEL_SERVICE_NAME: "frauddetectionservice"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-demo-otelcol:4318"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=frauddetectionservice,service.namespace=opentelemetry-demo,service.version=1.12.0"
  KAFKA_SERVICE_ADDR: "kafka:9092"
  FLAGD_HOST: "flagd"
  FLAGD_PORT: "8013"