apiVersion: v1
kind: ConfigMap
metadata:
  name: productreviewservice-config
data:
  OTEL_SERVICE_NAME: "productreviewservice"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-demo-otelcol:4318"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=productreviewservice,service.namespace=opentelemetry-demo,service.version=1.12.0"
  OTEL_PYTHON_LOG_CORRELATION: "true"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"

  LLM_BASE_URL: "http://llmservice:8080/v1"
  LLM_MODEL: "mock"
  LLM_HOST: "llmservice"
  LLM_PORT: "8080"

  PRODUCT_CATALOG_ADDR: "http://productcatalogservice:8080"

  PRODUCT_REVIEW_SERVICE_PORT: "8080"
  PRODUCT_REVIEWS_PORT: "8080"