---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: productreviewservice-secret
  namespace: ecommerce-dev
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgCwvXK3gxlgRLoiQ4XSj9StUWp0Y7Z4AnB27MkMFwVekbeTtUVuqEowNzEo8Cxhi+L7SI+QpCg+cVgvRR7Ty3Ha8lgWQsaDxH/q0v2GJXVrCdYaLOayEFvbFP/fDhI2W8wLzgvYTqlMKqY0tFMJqU5oehztmbfuA8OzbExjq7yuALyX2kpX/UBiVgocFdPswOoMi73O4pj5orXaIlq5MVMruCynlhNXkZGeHm7l/FZD1E/GCutKCVKL8cIALRVpLP7//zkbZflEFN6YbrAYmkMygOC6Sr9RYy7nDaHwTDqXZLL0QSHcJGc7/KJNjdu65iNaAXyiGlmc2fF1tHfA5f/zmJSQm+ebnM98YLGg5lDpK0vMpqUY9C6rJLhKp0OXGitObVy/Nvh2wOG5zjp3yNq/xO1fdv0hywyff0aileQOH9JuOPJQmFnvYO71URbxbdBCQn41SFmK3yM9XkZt65Ex4OyBAARQaSC6Ep2UV1SjNslP305GGaBxvzTUjnLHg+vv97zTNC8hoiIhivXN8iIJ3I6Z4zjTRms8JHGfBRYPmaT/k+5a4uA6alb/hg7Qms+1W4R2eqga/cZ46CqjDsJrU70+pzQ8okQn2hntfTVFFMP08vR/yPltZl64tSDDa0/o6XP9V2Ta8zY0lzNbOee2GBGBbNHdYJJyF/mA/kwlIfzSpMhOkpsy2LF9WkdanBJg2EoiwxqovnXLLhsxtQaZsK/5HkWn9E22u4Ng2a5scCDNVvtWj0gWv4LR
    OPENAI_API_KEY: AgC7LM2uNrQw0yQR+JH9kkCIWmvyZ8kpXRedgfL9Sl6LHAUUAuQqd4vcUtnDVrndWifUeTkTgfT3QdrY0Y5EaWAAVlluRL7/PO8DhLNbsP9KfbGAnsKkZhhZU20c1RuWKGuUVanO31lmHDdfyvBHPKzJDxYrN9MmTArkfr7PVOl8tfkPM/q+YMit82sw23c5hSSj/Snv2qiOWT7/zJQrS9+04J7qDzX3YfQw/9MQi2NOt29l9rg4vEkhrqMLXyH4YhNoeQr40/ffhaxalggabj+BuhXwcR0yJq2cpQDLWtdyNmm2HCbdGz3IrQaqzaA0C2wjHvdreS/WH0JiCF8eXYYPKjqaSK3QJ2esQLl/QJ4mLI8qHgxc+hWrbaG737+kfyNMXooYlg1VDiyzRu6G8Pe6zy8WJpxK3K/46+7JE2IXI3a++ivJVXMuEFRVbRx9wENf6A7nWf4Y/wvunNkmKX8uB0ahSIZdt/TyHp4yEgRnMkEBMZjtPcqETDyc74G/X69pMCkJeGLvzUIMeZ7YXgwCgi7Pb+AzdHU6SJtlT5XP2PZKZ8duBWP/1WW59Bor0ZCQjJP3U4lmepm/w+pZFxUxGP9Wo1O4ztmzBNA7nb4IR9Ewa8tLShZpx+eKDUj/PIoJbX/j6bteM+gDc7EUSVCboYHLRXPkW+HnDjZFEej6UpioUtDsAPVK6F7C78en7Eq5y+4DY70=
  template:
    metadata:
      name: productreviewservice-secret
      namespace: ecommerce-dev
    type: Opaque
