apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  POSTGRES_USER: "otel"
  POSTGRES_PASSWORD: "otel"
  POSTGRES_DB: "otel"
  DATABASE_URL: "postgresql://otel:otel@postgresql:5432/otel"